In [1]:
# Dependencies and setup.
import os
import csv
import pandas as pd

# Import ethnicity data.
path_eth15 = os.path.join("Enrollment Report_Statewide_Campuses_Ethnicity_2014-2015.csv")
path_eth16 = os.path.join("Enrollment Report_Statewide_Campuses_Ethnicity_2015-2016.csv")
path_eth17 = os.path.join("Enrollment Report_Statewide_Campuses_Ethnicity_2016-2017.csv")
path_eth18 = os.path.join("Enrollment Report_Statewide_Campuses_Ethnicity_2017-2018.csv")
path_eth19 = os.path.join("Enrollment Report_Statewide_Campuses_Ethnicity_2018-2019.csv")

# Convert ethnicity data to pandas data frame.
df_eth15 = pd.read_csv(path_eth15)
df_eth16 = pd.read_csv(path_eth16)
df_eth17 = pd.read_csv(path_eth17)
df_eth18 = pd.read_csv(path_eth18)
df_eth19 = pd.read_csv(path_eth19)

In [2]:
# Display first dataframe to understand data structure.
df_eth15

,Year,Region,County Name,District Name,District Number,Campus Name,Campus Number,Ethnicity Name,Enrollment by Ethnicity
0,2014-2015,1,HIDALGO COUNTY,DONNA ISD,108902,3D ACADEMY,108902006,Hispanic,87
1,2014-2015,10,HUNT COUNTY,GREENVILLE ISD,116905,6TH GRADE CENTER,116905108,Black or African American,53
2,2014-2015,10,HUNT COUNTY,GREENVILLE ISD,116905,6TH GRADE CENTER,116905108,American Indian or Alaska Native,-9999999
3,2014-2015,10,HUNT COUNTY,GREENVILLE ISD,116905,6TH GRADE CENTER,116905108,Asian,-9999999
4,2014-2015,10,HUNT COUNTY,GREENVILLE ISD,116905,6TH GRADE CENTER,116905108,Hispanic,129
...,...,...,...,...,...,...,...,...,...
45889,2014-2015,4,HARRIS COUNTY,KLEIN ISD,101915,ZWINK EL,101915128,American Indian or Alaska Native,8
45890,2014-2015,4,HARRIS COUNTY,KLEIN ISD,101915,ZWINK EL,101915128,Asian,57
45891,2014-2015,4,HARRIS COUNTY,KLEIN ISD,101915,ZWINK EL,101915128,Hispanic,369
45892,2014-2015,4,HARRIS COUNTY,KLEIN ISD,101915,ZWINK EL,101915128,Two or More Races,29
45893,2014-2015,4,HARRIS COUNTY,KLEIN ISD,101915,ZWINK EL,101915128,White,366

In [3]:
# Filter each dataframes to display only Travis County ethnicity data.

df_eth15_travis = df_eth15.loc[df_eth15["County Name"] == "TRAVIS COUNTY"]
df_eth15_travis = df_eth15_travis.drop(df_eth15_travis.columns[1], axis=1)
df_eth15_travis

,Year,County Name,District Name,District Number,Campus Name,Campus Number,Ethnicity Name,Enrollment by Ethnicity
342,2014-2015,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Asian,-9999999
343,2014-2015,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Hispanic,5
344,2014-2015,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Two or More Races,-9999999
345,2014-2015,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,White,31
423,2014-2015,TRAVIS COUNTY,AUSTIN ISD,227901,AKINS H S,227901017,Black or African American,193
...,...,...,...,...,...,...,...,...
45861,2014-2015,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,American Indian or Alaska Native,-9999999
45862,2014-2015,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,Asian,10
45863,2014-2015,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,Hispanic,207
45864,2014-2015,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,Two or More Races,27
45865,2014-2015,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,White,307

In [4]:
df_eth16_travis = df_eth16.loc[df_eth16["County Name"] == "TRAVIS COUNTY"]
df_eth16_travis = df_eth16_travis.drop(df_eth16_travis.columns[1], axis=1)
df_eth16_travis

,Year,County Name,District Name,District Number,Campus Name,Campus Number,Ethnicity Name,Enrollment by Ethnicity
333,2015-2016,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Asian,-9999999
334,2015-2016,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Hispanic,5
335,2015-2016,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,White,20
417,2015-2016,TRAVIS COUNTY,AUSTIN ISD,227901,AKINS H S,227901017,Black or African American,222
418,2015-2016,TRAVIS COUNTY,AUSTIN ISD,227901,AKINS H S,227901017,American Indian or Alaska Native,-9999999
...,...,...,...,...,...,...,...,...
46116,2015-2016,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,Black or African American,6
46117,2015-2016,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,Asian,5
46118,2015-2016,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,Hispanic,185
46119,2015-2016,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,Two or More Races,30
46120,2015-2016,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,White,312

In [5]:
df_eth17_travis = df_eth17.loc[df_eth17["County Name"] == "TRAVIS COUNTY"]
df_eth17_travis = df_eth17_travis.drop(df_eth17_travis.columns[[1, 7]], axis=1)
df_eth17_travis

,Year,County Name,District Name,District Number,Campus Name,Campus Number,Ethnicity Name,Enrollment by Ethnicity
332,2016-2017,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Black or African American,-9999999
333,2016-2017,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Asian,-9999999
334,2016-2017,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Hispanic,5
335,2016-2017,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Two or More Races,-9999999
336,2016-2017,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,White,19
...,...,...,...,...,...,...,...,...
46540,2016-2017,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,Black or African American,10
46541,2016-2017,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,Asian,-9999999
46542,2016-2017,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,Hispanic,195
46543,2016-2017,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,Two or More Races,29
46544,2016-2017,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,White,324

In [6]:
df_eth18_travis = df_eth18.loc[df_eth18["County Name"] == "TRAVIS COUNTY"]
df_eth18_travis = df_eth18_travis.drop(df_eth18_travis.columns[[1, 7]], axis=1)
df_eth18_travis

,Year,County Name,District Name,District Number,Campus Name,Campus Number,Ethnicity Name,Enrollment by Ethnicity
341,2017-2018,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Black or African American,-9999999
342,2017-2018,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Asian,-9999999
343,2017-2018,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Hispanic,-9999999
344,2017-2018,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Two or More Races,-9999999
345,2017-2018,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,White,13
...,...,...,...,...,...,...,...,...
46811,2017-2018,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,American Indian or Alaska Native,-9999999
46812,2017-2018,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,Asian,9
46813,2017-2018,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,Hispanic,179
46814,2017-2018,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,Two or More Races,29
46815,2017-2018,TRAVIS COUNTY,AUSTIN ISD,227901,ZILKER EL,227901146,White,322

In [7]:
# Displaying 5th dataframe for 2018-2019 ethnicity data reveals differences compared to other years in column order, column names and fonts.

df_eth19_travis = df_eth19.loc[df_eth19["COUNTY NAME"] == "TRAVIS COUNTY"]
df_eth19_travis

,YEAR,REGION,COUNTY NAME,DISTRICT,DISTRICT NAME,CAMPUS,CAMPUS NAME,ETHNICITY,GRADE GROUP NAME,ENROLLMENT
42464,2018-2019,13,TRAVIS COUNTY,227803,WAYSIDE SCHOOLS,227803001,WAYSIDE SCI-TECH MIDDLE AND H S,American Indian or Alaska Nat,ELEMENTARY / SECONDARY,1
42465,2018-2019,13,TRAVIS COUNTY,227803,WAYSIDE SCHOOLS,227803001,WAYSIDE SCI-TECH MIDDLE AND H S,Asian,ELEMENTARY / SECONDARY,6
42466,2018-2019,13,TRAVIS COUNTY,227803,WAYSIDE SCHOOLS,227803001,WAYSIDE SCI-TECH MIDDLE AND H S,Black or African American,ELEMENTARY / SECONDARY,30
42467,2018-2019,13,TRAVIS COUNTY,227803,WAYSIDE SCHOOLS,227803001,WAYSIDE SCI-TECH MIDDLE AND H S,Hispanic/Latino,ELEMENTARY / SECONDARY,479
42468,2018-2019,13,TRAVIS COUNTY,227803,WAYSIDE SCHOOLS,227803001,WAYSIDE SCI-TECH MIDDLE AND H S,Two or more races,ELEMENTARY / SECONDARY,7
...,...,...,...,...,...,...,...,...,...,...
44207,2018-2019,13,TRAVIS COUNTY,227913,LAKE TRAVIS ISD,227913106,WEST CYPRESS HILLS EL,Black or African American,ELEMENTARY,9
44208,2018-2019,13,TRAVIS COUNTY,227913,LAKE TRAVIS ISD,227913106,WEST CYPRESS HILLS EL,Hispanic/Latino,ELEMENTARY,116
44209,2018-2019,13,TRAVIS COUNTY,227913,LAKE TRAVIS ISD,227913106,WEST CYPRESS HILLS EL,Native Hawaiian/Other Pacific,ELEMENTARY,2
44210,2018-2019,13,TRAVIS COUNTY,227913,LAKE TRAVIS ISD,227913106,WEST CYPRESS HILLS EL,Two or more races,ELEMENTARY,51
44211,2018-2019,13,TRAVIS COUNTY,227913,LAKE TRAVIS ISD,227913106,WEST CYPRESS HILLS EL,White,ELEMENTARY,645

In [8]:
# Change 2018-2019 Travis County ethnicity data column name font to match other years.

df_eth19.columns = map(str.title, df_eth19.columns)
df_eth19

,Year,Region,County Name,District,District Name,Campus,Campus Name,Ethnicity,Grade Group Name,Enrollment
0,2018-2019,7,ANDERSON COUNTY,1902,CAYUGA ISD,1902001,CAYUGA H S,Black or African American,HIGH SCHOOL,5
1,2018-2019,7,ANDERSON COUNTY,1902,CAYUGA ISD,1902001,CAYUGA H S,Hispanic/Latino,HIGH SCHOOL,10
2,2018-2019,7,ANDERSON COUNTY,1902,CAYUGA ISD,1902001,CAYUGA H S,Two or more races,HIGH SCHOOL,12
3,2018-2019,7,ANDERSON COUNTY,1902,CAYUGA ISD,1902001,CAYUGA H S,White,HIGH SCHOOL,152
4,2018-2019,7,ANDERSON COUNTY,1902,CAYUGA ISD,1902041,CAYUGA MIDDLE,Asian,MIDDLE SCHOOL,1
...,...,...,...,...,...,...,...,...,...,...
47290,2018-2019,20,ZAVALA COUNTY,254901,CRYSTAL CITY ISD,254901106,ZAVALA EL,White,ELEMENTARY,1
47291,2018-2019,20,ZAVALA COUNTY,254902,LA PRYOR ISD,254902001,LA PRYOR H S,Hispanic/Latino,HIGH SCHOOL,211
47292,2018-2019,20,ZAVALA COUNTY,254902,LA PRYOR ISD,254902001,LA PRYOR H S,White,HIGH SCHOOL,4
47293,2018-2019,20,ZAVALA COUNTY,254902,LA PRYOR ISD,254902101,LA PRYOR EL,Hispanic/Latino,ELEMENTARY,279
47294,2018-2019,20,ZAVALA COUNTY,254902,LA PRYOR ISD,254902101,LA PRYOR EL,White,ELEMENTARY,9

In [11]:
# Change 2018-2019 Travis County ethnicity data column names to match other years.

df_eth19.rename(columns = {"Year":"Year", "Region":"Region", "County Name":"County Name", "District":"District Number",
                          "District Name":"District Name", "Campus":"Campus Number", "Campus Name":"Campus Name", "Ethnicity":"Ethnicity Name",
                           "Enrollment":"Enrollment by Ethnicity" }, inplace = True) 
df_eth19

,Year,Region,County Name,District Number,District Name,Campus Number,Campus Name,Ethnicity Name,Grade Group Name,Enrollment by Ethnicity
0,2018-2019,7,ANDERSON COUNTY,1902,CAYUGA ISD,1902001,CAYUGA H S,Black or African American,HIGH SCHOOL,5
1,2018-2019,7,ANDERSON COUNTY,1902,CAYUGA ISD,1902001,CAYUGA H S,Hispanic/Latino,HIGH SCHOOL,10
2,2018-2019,7,ANDERSON COUNTY,1902,CAYUGA ISD,1902001,CAYUGA H S,Two or more races,HIGH SCHOOL,12
3,2018-2019,7,ANDERSON COUNTY,1902,CAYUGA ISD,1902001,CAYUGA H S,White,HIGH SCHOOL,152
4,2018-2019,7,ANDERSON COUNTY,1902,CAYUGA ISD,1902041,CAYUGA MIDDLE,Asian,MIDDLE SCHOOL,1
...,...,...,...,...,...,...,...,...,...,...
47290,2018-2019,20,ZAVALA COUNTY,254901,CRYSTAL CITY ISD,254901106,ZAVALA EL,White,ELEMENTARY,1
47291,2018-2019,20,ZAVALA COUNTY,254902,LA PRYOR ISD,254902001,LA PRYOR H S,Hispanic/Latino,HIGH SCHOOL,211
47292,2018-2019,20,ZAVALA COUNTY,254902,LA PRYOR ISD,254902001,LA PRYOR H S,White,HIGH SCHOOL,4
47293,2018-2019,20,ZAVALA COUNTY,254902,LA PRYOR ISD,254902101,LA PRYOR EL,Hispanic/Latino,ELEMENTARY,279
47294,2018-2019,20,ZAVALA COUNTY,254902,LA PRYOR ISD,254902101,LA PRYOR EL,White,ELEMENTARY,9

In [12]:
# Swap 2018-2019 Travis County ethnicity data column order (for District Number and District Name) to match other years.

cols1 = list(df_eth19.columns)
a, b = cols1.index("District Number"), cols1.index("District Name")
cols1[a], cols1[b] = cols1[b], cols1[a]
df_eth19 = df_eth19[cols1]

cols2 = list(df_eth19.columns)
c, d = cols2.index("Campus Number"), cols2.index("Campus Name")
cols2[c], cols2[d] = cols2[d], cols2[c]
df_eth19_clean = df_eth19[cols2]
df_eth19_clean

,Year,Region,County Name,District Name,District Number,Campus Name,Campus Number,Ethnicity Name,Grade Group Name,Enrollment by Ethnicity
0,2018-2019,7,ANDERSON COUNTY,CAYUGA ISD,1902,CAYUGA H S,1902001,Black or African American,HIGH SCHOOL,5
1,2018-2019,7,ANDERSON COUNTY,CAYUGA ISD,1902,CAYUGA H S,1902001,Hispanic/Latino,HIGH SCHOOL,10
2,2018-2019,7,ANDERSON COUNTY,CAYUGA ISD,1902,CAYUGA H S,1902001,Two or more races,HIGH SCHOOL,12
3,2018-2019,7,ANDERSON COUNTY,CAYUGA ISD,1902,CAYUGA H S,1902001,White,HIGH SCHOOL,152
4,2018-2019,7,ANDERSON COUNTY,CAYUGA ISD,1902,CAYUGA MIDDLE,1902041,Asian,MIDDLE SCHOOL,1
...,...,...,...,...,...,...,...,...,...,...
47290,2018-2019,20,ZAVALA COUNTY,CRYSTAL CITY ISD,254901,ZAVALA EL,254901106,White,ELEMENTARY,1
47291,2018-2019,20,ZAVALA COUNTY,LA PRYOR ISD,254902,LA PRYOR H S,254902001,Hispanic/Latino,HIGH SCHOOL,211
47292,2018-2019,20,ZAVALA COUNTY,LA PRYOR ISD,254902,LA PRYOR H S,254902001,White,HIGH SCHOOL,4
47293,2018-2019,20,ZAVALA COUNTY,LA PRYOR ISD,254902,LA PRYOR EL,254902101,Hispanic/Latino,ELEMENTARY,279
47294,2018-2019,20,ZAVALA COUNTY,LA PRYOR ISD,254902,LA PRYOR EL,254902101,White,ELEMENTARY,9

In [17]:
# Filter 2018-2019 dataframe to display only Travis County ethnicity data.

df_eth19_clean_travis = df_eth19_clean.loc[df_eth19_clean["County Name"] == "TRAVIS COUNTY"]
df_eth19_clean_travis = df_eth19_clean_travis.drop(df_eth19_clean_travis.columns[[1, 8]], axis=1)
df_eth19_clean_travis

,Year,County Name,District Name,District Number,Campus Name,Campus Number,Ethnicity Name,Enrollment by Ethnicity
42464,2018-2019,TRAVIS COUNTY,WAYSIDE SCHOOLS,227803,WAYSIDE SCI-TECH MIDDLE AND H S,227803001,American Indian or Alaska Nat,1
42465,2018-2019,TRAVIS COUNTY,WAYSIDE SCHOOLS,227803,WAYSIDE SCI-TECH MIDDLE AND H S,227803001,Asian,6
42466,2018-2019,TRAVIS COUNTY,WAYSIDE SCHOOLS,227803,WAYSIDE SCI-TECH MIDDLE AND H S,227803001,Black or African American,30
42467,2018-2019,TRAVIS COUNTY,WAYSIDE SCHOOLS,227803,WAYSIDE SCI-TECH MIDDLE AND H S,227803001,Hispanic/Latino,479
42468,2018-2019,TRAVIS COUNTY,WAYSIDE SCHOOLS,227803,WAYSIDE SCI-TECH MIDDLE AND H S,227803001,Two or more races,7
...,...,...,...,...,...,...,...,...
44207,2018-2019,TRAVIS COUNTY,LAKE TRAVIS ISD,227913,WEST CYPRESS HILLS EL,227913106,Black or African American,9
44208,2018-2019,TRAVIS COUNTY,LAKE TRAVIS ISD,227913,WEST CYPRESS HILLS EL,227913106,Hispanic/Latino,116
44209,2018-2019,TRAVIS COUNTY,LAKE TRAVIS ISD,227913,WEST CYPRESS HILLS EL,227913106,Native Hawaiian/Other Pacific,2
44210,2018-2019,TRAVIS COUNTY,LAKE TRAVIS ISD,227913,WEST CYPRESS HILLS EL,227913106,Two or more races,51
44211,2018-2019,TRAVIS COUNTY,LAKE TRAVIS ISD,227913,WEST CYPRESS HILLS EL,227913106,White,645

In [18]:
# Concatenate all 5 years' dataframes for Travis County ethnicity data, and reset index to avoid duplicate indices.

df_eth5yrs_travis = pd.concat([df_eth15_travis, df_eth16_travis, df_eth17_travis, df_eth18_travis, df_eth19_clean_travis])
df_eth5yrs_travis=df_eth5yrs_travis.reset_index(drop=True)
df_eth5yrs_travis

,Year,County Name,District Name,District Number,Campus Name,Campus Number,Ethnicity Name,Enrollment by Ethnicity
0,2014-2015,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Asian,-9999999
1,2014-2015,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Hispanic,5
2,2014-2015,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,Two or More Races,-9999999
3,2014-2015,TRAVIS COUNTY,EANES ISD,227909,ADULT TRANSITION SERVICES,227909005,White,31
4,2014-2015,TRAVIS COUNTY,AUSTIN ISD,227901,AKINS H S,227901017,Black or African American,193
...,...,...,...,...,...,...,...,...
7525,2018-2019,TRAVIS COUNTY,LAKE TRAVIS ISD,227913,WEST CYPRESS HILLS EL,227913106,Black or African American,9
7526,2018-2019,TRAVIS COUNTY,LAKE TRAVIS ISD,227913,WEST CYPRESS HILLS EL,227913106,Hispanic/Latino,116
7527,2018-2019,TRAVIS COUNTY,LAKE TRAVIS ISD,227913,WEST CYPRESS HILLS EL,227913106,Native Hawaiian/Other Pacific,2
7528,2018-2019,TRAVIS COUNTY,LAKE TRAVIS ISD,227913,WEST CYPRESS HILLS EL,227913106,Two or more races,51
7529,2018-2019,TRAVIS COUNTY,LAKE TRAVIS ISD,227913,WEST CYPRESS HILLS EL,227913106,White,645

In [20]:
# Output to a CSV file the final concatenated dataframe for 5 years of Travis County ethnicity data.

df_eth5yrs_travis.to_csv("Output_ethnicity_5yrs_Travis.csv", index=False)

In [ ]:
isd_list = df_eth5yrs_travis["District Name"].unique()
isd_list

In [ ]:
ethnicity_list = df_eth5yrs_travis["Ethnicity Name"].unique()
ethnicity_list

In [ ]:
df_eth5yrs_travis.loc["District Name"]["Black or African American']