In [1]:
#dependencies and set up
import os
import pandas as pd

%load_ext nb_black

In [2]:
#create paths for each csv to clean 1 at a time
path_1 = "Resources/School_Meal_Reimbursement_Year_2015-2016.csv"
path_2 = "Resources/School_Meal_Reimbursement_Year_2016-2017.csv"
path_3 = "Resources/School_Meal_Reimbursement_Year_2017-2018.csv"
path_4 = "Resources/School_Meal_Reimbursement_Year_2018-2019.csv"

In [3]:
#import and read first csv
#columns were initially colapsed, use dispay.max_columns to view all
pd.set_option('display.max_columns', None)
df_1 = pd.read_csv(path_1)
df_1.head()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (34,36,40) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ProgramYear,ReportType,CEID,CEName,CECounty,ESC,TDARegion,TypeOfAgency,TypeOfSNPOrg,SiteID,SiteName,SiteCounty,ClaimDate,EnrollmentQty,FreeEligibleQty,ReducedEligibleQty,PaidEligibleQty,BreakfastDays,BreakfastTotal,BreakfastADP,BreakfastServedFree,BreakfastServedReduced,BreakfastServedPaid,LunchDays,LunchTotal,LunchADP,LunchServedFree,LunchServedReduced,LunchServedPaid,SnackDays,SnackTotal,SnackADP,SnackServedFree,SnackServedReduced,SnackServedPaid,MilkDays,Milktotal,MilkADP,MilkServedFree,MilkServedReduced,MilkServedPaid,BreakfastReimbursement,LunchReimbursement,SnackReimbursement,MilkReimbursement,TotalReimbursement
0,2015-2016,SCHOOLNUTRITIONPROGRAMCLAIMS,1,CAYUGA ISD,ANDERSON,7.0,2.0,Educational Institution,Public,1,CAYUGA H S,ANDERSON,08/01/2015 12:00:00 AM,191,55,10,126,6,240,40,94,26,120,6,556,92.67,185,37,334,0,0,0.0,0,0,0,0,0,0.0,0,0,0,265.8,796.96,0,0.0,"1,062.76"
1,2015-2016,SCHOOLNUTRITIONPROGRAMCLAIMS,1,CAYUGA ISD,ANDERSON,7.0,2.0,Educational Institution,Public,1,CAYUGA H S,ANDERSON,09/01/2015 12:00:00 AM,186,55,10,121,21,855,40.71,373,91,391,21,"1,705",81.19,626,115,964,0,0,0.0,0,0,0,0,0,0.0,0,0,0,"1,009.45","2,610.73",0,0.0,"3,620.18"
2,2015-2016,SCHOOLNUTRITIONPROGRAMCLAIMS,1,CAYUGA ISD,ANDERSON,7.0,2.0,Educational Institution,Public,1,CAYUGA H S,ANDERSON,10/01/2015 12:00:00 AM,186,44,13,129,21,866,41.24,398,80,388,21,"1,618",77.05,574,127,917,0,0,0.0,0,0,0,0,0,0.0,0,0,0,"1,039.74","2,464.28",0,0.0,"3,504.02"
3,2015-2016,SCHOOLNUTRITIONPROGRAMCLAIMS,1,CAYUGA ISD,ANDERSON,7.0,2.0,Educational Institution,Public,1,CAYUGA H S,ANDERSON,11/01/2015 12:00:00 AM,187,42,11,134,18,805,44.72,336,95,374,18,"1,542",85.67,489,128,925,0,0,0.0,0,0,0,0,0,0.0,0,0,0,937.65,"2,203.76",0,0.0,"3,141.41"
4,2015-2016,SCHOOLNUTRITIONPROGRAMCLAIMS,1,CAYUGA ISD,ANDERSON,7.0,2.0,Educational Institution,Public,1,CAYUGA H S,ANDERSON,12/01/2015 12:00:00 AM,186,42,11,133,14,539,38.5,234,44,261,14,"1,040",74.29,351,86,603,0,0,0.0,0,0,0,0,0,0.0,0,0,0,615.71,"1,544.46",0,0.0,"2,160.17"

In [4]:
#drop all columns not needed for analysis (only need quantity of students and quantity that qualifies for free or reduced lunch)
df_1.drop(columns=["ReportType", "ESC", "TDARegion", "SiteID", "SiteCounty", "BreakfastDays", "BreakfastTotal", 
                   "BreakfastADP", "BreakfastServedFree", "BreakfastServedReduced", "BreakfastServedPaid", 
                   "LunchDays", "LunchTotal", "LunchADP", "LunchServedFree", "LunchServedReduced",
                   "LunchServedPaid", "SnackDays", "SnackTotal", "SnackADP", "SnackServedFree",
                  "SnackServedReduced", "SnackServedPaid", "MilkDays", "Milktotal", "MilkADP",
                  "MilkServedFree", "MilkServedReduced", "MilkServedPaid", "BreakfastReimbursement",
                  "LunchReimbursement", "SnackReimbursement", "MilkReimbursement"], inplace=True)

In [5]:
df_1

,ProgramYear,CEID,CEName,CECounty,TypeOfAgency,TypeOfSNPOrg,SiteName,ClaimDate,EnrollmentQty,FreeEligibleQty,ReducedEligibleQty,PaidEligibleQty,TotalReimbursement
0,2015-2016,1,CAYUGA ISD,ANDERSON,Educational Institution,Public,CAYUGA H S,08/01/2015 12:00:00 AM,191,55,10,126,"1,062.76"
1,2015-2016,1,CAYUGA ISD,ANDERSON,Educational Institution,Public,CAYUGA H S,09/01/2015 12:00:00 AM,186,55,10,121,"3,620.18"
2,2015-2016,1,CAYUGA ISD,ANDERSON,Educational Institution,Public,CAYUGA H S,10/01/2015 12:00:00 AM,186,44,13,129,"3,504.02"
3,2015-2016,1,CAYUGA ISD,ANDERSON,Educational Institution,Public,CAYUGA H S,11/01/2015 12:00:00 AM,187,42,11,134,"3,141.41"
4,2015-2016,1,CAYUGA ISD,ANDERSON,Educational Institution,Public,CAYUGA H S,12/01/2015 12:00:00 AM,186,42,11,133,"2,160.17"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89899,2015-2016,5446,TEXAS SAN MARCOS TREATMENT CENTER,HAYS,Other,RCCI,TEXAS SAN MARCOS TREATMENT CENTER,05/01/2016 12:00:00 AM,191,191,0,0,"26,037.61"
89900,2015-2016,5446,TEXAS SAN MARCOS TREATMENT CENTER,HAYS,Other,RCCI,TEXAS SAN MARCOS TREATMENT CENTER,06/01/2016 12:00:00 AM,186,186,0,0,"24,221.35"
89901,2015-2016,5465,LEARNING SCHOOLS OF TEXAS,BEXAR,Educational Institution,Charter,CARPE DIEM SCHOOLS,04/01/2016 12:00:00 AM,218,122,16,80,"3,952.19"
89902,2015-2016,5465,LEARNING SCHOOLS OF TEXAS,BEXAR,Educational Institution,Charter,CARPE DIEM SCHOOLS,05/01/2016 12:00:00 AM,215,120,17,78,"3,632.4"
89903,2015-2016,5465,LEARNING SCHOOLS OF TEXAS,BEXAR,Educational Institution,Charter,CARPE DIEM SCHOOLS,06/01/2016 12:00:00 AM,215,120,17,78,469.55