In [3]:
#dependencies and set up
import os
import pandas as pd

%load_ext nb_black

In [25]:
#create paths for each csv to clean 1 at a time
path_1 = "Resources/School_Meal_Reimbursement_Year_2015-2016.csv"
path_2 = "Resources/School_Meal_Reimbursement_Year_2016-2017.csv"
path_3 = "Resources/School_Meal_Reimbursement_Year_2017-2018.csv"
path_4 = "Resources/School_Meal_Reimbursement_Year_2018-2019.csv"

#create out paths for cleaned csv files
out_path_1 = "Resources/clean_meal_reimbursement_year_2015_16.csv"
out_path_2 = "Resources/clean_meal_reimbursement_year_2016_17.csv"
out_path_3 = "Resources/clean_meal_reimbursement_year_2017_18.csv"
out_path_4 = "Resources/clean_meal_reimbursement_year_2018_19.csv"

In [5]:
#import and read first csv for 2015 - 2016 data
#columns were initially colapsed, use dispay.max_columns to view all
pd.set_option('display.max_columns', None)
df_1 = pd.read_csv(path_1)
df_1.head()

/opt/conda/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (34,36,40) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,ProgramYear,ReportType,CEID,CEName,CECounty,ESC,TDARegion,TypeOfAgency,TypeOfSNPOrg,SiteID,SiteName,SiteCounty,ClaimDate,EnrollmentQty,FreeEligibleQty,ReducedEligibleQty,PaidEligibleQty,BreakfastDays,BreakfastTotal,BreakfastADP,BreakfastServedFree,BreakfastServedReduced,BreakfastServedPaid,LunchDays,LunchTotal,LunchADP,LunchServedFree,LunchServedReduced,LunchServedPaid,SnackDays,SnackTotal,SnackADP,SnackServedFree,SnackServedReduced,SnackServedPaid,MilkDays,Milktotal,MilkADP,MilkServedFree,MilkServedReduced,MilkServedPaid,BreakfastReimbursement,LunchReimbursement,SnackReimbursement,MilkReimbursement,TotalReimbursement
0,2015-2016,SCHOOLNUTRITIONPROGRAMCLAIMS,1,CAYUGA ISD,ANDERSON,7.0,2.0,Educational Institution,Public,1,CAYUGA H S,ANDERSON,08/01/2015 12:00:00 AM,191,55,10,126,6,240,40,94,26,120,6,556,92.67,185,37,334,0,0,0.0,0,0,0,0,0,0.0,0,0,0,265.8,796.96,0,0.0,"1,062.76"
1,2015-2016,SCHOOLNUTRITIONPROGRAMCLAIMS,1,CAYUGA ISD,ANDERSON,7.0,2.0,Educational Institution,Public,1,CAYUGA H S,ANDERSON,09/01/2015 12:00:00 AM,186,55,10,121,21,855,40.71,373,91,391,21,"1,705",81.19,626,115,964,0,0,0.0,0,0,0,0,0,0.0,0,0,0,"1,009.45","2,610.73",0,0.0,"3,620.18"
2,2015-2016,SCHOOLNUTRITIONPROGRAMCLAIMS,1,CAYUGA ISD,ANDERSON,7.0,2.0,Educational Institution,Public,1,CAYUGA H S,ANDERSON,10/01/2015 12:00:00 AM,186,44,13,129,21,866,41.24,398,80,388,21,"1,618",77.05,574,127,917,0,0,0.0,0,0,0,0,0,0.0,0,0,0,"1,039.74","2,464.28",0,0.0,"3,504.02"
3,2015-2016,SCHOOLNUTRITIONPROGRAMCLAIMS,1,CAYUGA ISD,ANDERSON,7.0,2.0,Educational Institution,Public,1,CAYUGA H S,ANDERSON,11/01/2015 12:00:00 AM,187,42,11,134,18,805,44.72,336,95,374,18,"1,542",85.67,489,128,925,0,0,0.0,0,0,0,0,0,0.0,0,0,0,937.65,"2,203.76",0,0.0,"3,141.41"
4,2015-2016,SCHOOLNUTRITIONPROGRAMCLAIMS,1,CAYUGA ISD,ANDERSON,7.0,2.0,Educational Institution,Public,1,CAYUGA H S,ANDERSON,12/01/2015 12:00:00 AM,186,42,11,133,14,539,38.5,234,44,261,14,"1,040",74.29,351,86,603,0,0,0.0,0,0,0,0,0,0.0,0,0,0,615.71,"1,544.46",0,0.0,"2,160.17"

In [6]:
#drop all columns not needed for analysis (only need quantity of students and quantity that qualifies for free or reduced lunch)
df_1.drop(columns=["ReportType", "ESC", "TDARegion", "SiteID", "SiteCounty", "BreakfastDays", "BreakfastTotal", 
                   "BreakfastADP", "BreakfastServedFree", "BreakfastServedReduced", "BreakfastServedPaid", 
                   "LunchDays", "LunchTotal", "LunchADP", "LunchServedFree", "LunchServedReduced",
                   "LunchServedPaid", "SnackDays", "SnackTotal", "SnackADP", "SnackServedFree",
                  "SnackServedReduced", "SnackServedPaid", "MilkDays", "Milktotal", "MilkADP",
                  "MilkServedFree", "MilkServedReduced", "MilkServedPaid", "BreakfastReimbursement",
                  "LunchReimbursement", "SnackReimbursement", "MilkReimbursement"], inplace=True)

In [7]:
df_1.head()

,ProgramYear,CEID,CEName,CECounty,TypeOfAgency,TypeOfSNPOrg,SiteName,ClaimDate,EnrollmentQty,FreeEligibleQty,ReducedEligibleQty,PaidEligibleQty,TotalReimbursement
0,2015-2016,1,CAYUGA ISD,ANDERSON,Educational Institution,Public,CAYUGA H S,08/01/2015 12:00:00 AM,191,55,10,126,"1,062.76"
1,2015-2016,1,CAYUGA ISD,ANDERSON,Educational Institution,Public,CAYUGA H S,09/01/2015 12:00:00 AM,186,55,10,121,"3,620.18"
2,2015-2016,1,CAYUGA ISD,ANDERSON,Educational Institution,Public,CAYUGA H S,10/01/2015 12:00:00 AM,186,44,13,129,"3,504.02"
3,2015-2016,1,CAYUGA ISD,ANDERSON,Educational Institution,Public,CAYUGA H S,11/01/2015 12:00:00 AM,187,42,11,134,"3,141.41"
4,2015-2016,1,CAYUGA ISD,ANDERSON,Educational Institution,Public,CAYUGA H S,12/01/2015 12:00:00 AM,186,42,11,133,"2,160.17"

In [8]:
#create series of rows for schools only in Travis county
travis_co_1 = df_1.loc[df_1["CECounty"] == "TRAVIS"]

#count the number of districts to match up with ethnicity data for consistency
travis_co_1["CEName"].nunique()

25

In [9]:
travis_co_1.dtypes

ProgramYear           object
CEID                   int64
CEName                object
CECounty              object
TypeOfAgency          object
TypeOfSNPOrg          object
SiteName              object
ClaimDate             object
EnrollmentQty         object
FreeEligibleQty       object
ReducedEligibleQty     int64
PaidEligibleQty       object
TotalReimbursement    object
dtype: object

In [10]:
#replace commas with "" to fix unable to parse string error
travis_co_1 = travis_co_1.replace(',','', regex=True)
travis_co_1.head()

,ProgramYear,CEID,CEName,CECounty,TypeOfAgency,TypeOfSNPOrg,SiteName,ClaimDate,EnrollmentQty,FreeEligibleQty,ReducedEligibleQty,PaidEligibleQty,TotalReimbursement
77951,2015-2016,1057,WAYSIDE SCHOOLS,TRAVIS,Educational Institution,Charter,WAYSIDE SCI-TECH MIDDLE AND H S,07/01/2015 12:00:00 AM,435,238,39,158,1739.31
77952,2015-2016,1057,WAYSIDE SCHOOLS,TRAVIS,Educational Institution,Charter,WAYSIDE SCI-TECH MIDDLE AND H S,08/01/2015 12:00:00 AM,443,231,40,172,8938.02
77953,2015-2016,1057,WAYSIDE SCHOOLS,TRAVIS,Educational Institution,Charter,WAYSIDE SCI-TECH MIDDLE AND H S,09/01/2015 12:00:00 AM,434,213,36,185,8071.61
77954,2015-2016,1057,WAYSIDE SCHOOLS,TRAVIS,Educational Institution,Charter,WAYSIDE SCI-TECH MIDDLE AND H S,10/01/2015 12:00:00 AM,431,216,37,178,6439.05
77955,2015-2016,1057,WAYSIDE SCHOOLS,TRAVIS,Educational Institution,Charter,WAYSIDE SCI-TECH MIDDLE AND H S,11/01/2015 12:00:00 AM,419,211,36,172,7361.79

In [11]:
#change datatypes for quantity and reimbursement columns before perfoming calculations
travis_co_1[["EnrollmentQty", "FreeEligibleQty", "PaidEligibleQty", "TotalReimbursement"]] = travis_co_1[["EnrollmentQty", "FreeEligibleQty", "PaidEligibleQty", "TotalReimbursement"]].apply(pd.to_numeric)

#check datatypes
travis_co_1.dtypes

ProgramYear            object
CEID                    int64
CEName                 object
CECounty               object
TypeOfAgency           object
TypeOfSNPOrg           object
SiteName               object
ClaimDate              object
EnrollmentQty           int64
FreeEligibleQty         int64
ReducedEligibleQty      int64
PaidEligibleQty         int64
TotalReimbursement    float64
dtype: object

In [20]:
#calcuate enrollment, free qty, reduced qty, paid qty, and total reiumbursement for each school for the entire school year
eligibility_by_school_15_16 = travis_co_1.groupby(["SiteName"]).agg({"ProgramYear": "first", 
                                      "CEID": "first", 
                                      "CEName": "first",
                                      "CECounty": "first",
                                      "TypeOfAgency": "first",
                                      "TypeOfSNPOrg": "first",
                                      "SiteName": "first",
                                      "ClaimDate": "last",
                                      "EnrollmentQty": "mean",
                                      "FreeEligibleQty": "mean",
                                      "ReducedEligibleQty": "mean",
                                      "PaidEligibleQty": "mean",
                                      "TotalReimbursement": "sum",
                                      })

In [26]:
#export to csv
eligibility_by_school_15_16.to_csv(out_path_1, index=False)